services:
  - type: web
    name: fastapi-webhook-server
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "uvicorn main:app --host 0.0.0.0 --port $PORT"
    plan: starter

  - type: worker
    name: webhook-tester
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python tester.py --endpoint https://fastapi-webhook-server.onrender.com/webhook/new-register --interval 15"
    plan: starter